name: Build and deploy .NET Core app to Azure Function App - silicon-account-provider

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to the function app project, defaults to repository root
  DOTNET_VERSION: '8.0.x' # .NET version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup DotNet ${{ env.DOTNET_VERSION }} Environment'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Restore Project Dependencies Using Dotnet'
        run: dotnet restore

      - name: 'Build Project Using Dotnet'
        run: dotnet build --configuration Release
        
      - name: 'Publish Project to Directory'
        run: dotnet publish --configuration Release --output ./output

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: 'silicon-account-provider'
          slot-name: 'Production'
          package: './output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0CF1F39B5890467F994B09B16B4A42BE }}
